version: '3.8'

services:
  backend:
    image: dashboard-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:3000" # Expose API on host 8080 -> container 3000
    environment:
      - PORT=3000
      - DATABASE_SERVER_PORT=80
    networks:
      - app-network

  frontend:
    image: dashboard-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=backend
      - BACKEND_PORT=3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
